// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzQdmyJL9EGBFWPFlAEKVBeuN4F9DLo8c',
    appId: '1:676476441933:android:75514516c73de42aae9304',
    messagingSenderId: '676476441933',
    projectId: 'makani-sandbox',
    storageBucket: 'makani-sandbox.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeAHjekbo-M6gE4RVpa9Hjz6Xq4orlxWs',
    appId: '1:676476441933:ios:233778ebadc73213ae9304',
    messagingSenderId: '676476441933',
    projectId: 'makani-sandbox',
    storageBucket: 'makani-sandbox.appspot.com',
    androidClientId: '676476441933-g0hqfpcqleifj88fhr6838gum6n6nnsi.apps.googleusercontent.com',
    iosClientId: '676476441933-jpjhfmojpp70kmahicbeu3du3tcstpdq.apps.googleusercontent.com',
    iosBundleId: 'com.makanis.app',
  );
}
